# Generated by Django 5.2 on 2025-06-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='사건번호')),
                ('usage', models.CharField(max_length=100, verbose_name='용도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '매물',
                'verbose_name_plural': '매물들',
            },
        ),
        migrations.CreateModel(
            name='AutoBidReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, verbose_name='사건번호')),
                ('bid_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='입찰금액')),
                ('reserve_time', models.DateTimeField(verbose_name='예약시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자동입찰 예약',
                'verbose_name_plural': '자동입찰 예약들',
            },
        ),
        migrations.CreateModel(
            name='AutoBidFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, verbose_name='사건번호')),
                ('usage', models.CharField(max_length=100, verbose_name='용도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자동입찰 즐겨찾기',
                'verbose_name_plural': '자동입찰 즐겨찾기들',
                'unique_together': {('user', 'case_number')},
            },
        ),
    ]
