"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# decouple import 시도 및 fallback 처리
try:
    from decouple import config
except ImportError:
    def config(key, default=None, cast=str):
        return os.environ.get(key, default)

# Docker 환경 감지
DOCKER_ENV = os.environ.get('DOCKER_ENV', False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-co-ul@sm@&5r74m@79q8$^#knb=4*7o-#ic0sm+v^n!khfz0dr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # allauth를 위해 필요
    'django_extensions',
    
    # Third-party apps (allauth를 accounts보다 먼저)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'consult_app',  # consult_app 추가
    'chatbot',
    'rest_framework',
    'corsheaders',
    
    # Your apps (accounts를 다른 앱들보다 먼저)
    'accounts',  # Custom user model app
    'auth_api',
    'main',
    'app.apps.AuctionAppConfig',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add allauth middleware
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'main/templates',  # main app templates
            BASE_DIR / 'venv/Lib/site-packages/allauth/templates', # Re-adding explicit allauth path as APP_DIRS isn't working reliably
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Docker 환경 감지
DOCKER_ENV = os.environ.get('DOCKER_ENV', False)

if DOCKER_ENV:
    STATIC_ROOT = '/app/staticfiles'
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

# 실제 존재하는 static 디렉토리들 설정
STATICFILES_DIRS = [
    BASE_DIR / 'auth_api/static',
    BASE_DIR / 'main/static',
    BASE_DIR / 'chatbot/static',
]

# Media files
MEDIA_URL = '/media/'
if DOCKER_ENV:
    MEDIA_ROOT = '/app/media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Static files finder 설정
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5500',  # Your frontend development server origin
    # Add other origins if needed (e.g., your production frontend URL)
    'http://localhost:8000',
]

# Optional: Allow all origins (less secure, use only for testing)
# CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'accounts.User'

# Naver Maps API Settings
NAVER_MAPS_CLIENT_ID = 'nekr3y57xu'

# 이메일 백엔드 설정 (개발 중 콘솔 출력용)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 사이트 ID 설정
SITE_ID = 1

# 로그인/로그아웃 후 리디렉션 페이지
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Simple JWT 설정
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Use the project's SECRET_KEY
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Social Account Providers Settings
SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': '717318581cabe2d3d608ec057f0f82d5',
            'secret': '', # Add your Kakao secret if applicable
            'key': '' # Add your Kakao key if applicable
        }
    }
}

# Tell allauth to use our custom signup form
# ACCOUNT_SIGNUP_FORM_CLASS = 'main.forms.CustomSignupForm' # Removed this setting

# Use ACCOUNT_FORMS dictionary instead to avoid circular imports
ACCOUNT_FORMS = {
    'signup': 'main.forms.CustomSignupForm',
}


import os
from django.db.backends.signals import connection_created
from django.dispatch import receiver
from django.db import OperationalError

@receiver(connection_created)
def activate_sqlite_wal(sender, connection, **kwargs):
    # runserver 리로더 부모 프로세스나 migrations 체크 타이밍에 실행되지 않도록
    if os.environ.get('RUN_MAIN') != 'true':
        return

    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        try:
            cursor.execute('PRAGMA journal_mode=WAL;')
            cursor.execute('PRAGMA synchronous=NORMAL;')
            cursor.execute('PRAGMA busy_timeout=0;')
        except OperationalError:
            # 이미 락이 걸려 있으면 무시
            pass

# Docker 환경 감지
DOCKER_ENV = os.environ.get('DOCKER_ENV', False)

if DOCKER_ENV:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')
    
    # Redis 설정 (Docker 환경)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("redis", 6379)],
            },
        },
    }

# Static files settings for Docker
if DOCKER_ENV:
    STATIC_ROOT = '/app/staticfiles'
    MEDIA_ROOT = '/app/media'