# Generated by Django 5.2.1 on 2025-05-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionCase',
            fields=[
                ('case_number', models.CharField(help_text='사건번호', max_length=100, primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, help_text='사건명', max_length=255, null=True)),
                ('court_name', models.CharField(blank=True, help_text='법원', max_length=255, null=True)),
                ('filing_date', models.DateField(blank=True, help_text='접수일자', null=True)),
                ('responsible_dept', models.CharField(blank=True, help_text='담당계', max_length=255, null=True)),
                ('claim_amount', models.CharField(blank=True, help_text='청구금액', max_length=255, null=True)),
                ('appeal_status', models.BooleanField(blank=True, default=False, help_text='항고여부', null=True)),
                ('minimum_bid_price', models.CharField(blank=True, help_text='최저입찰가', max_length=255, null=True)),
            ],
            options={
                'db_table': 'auction_case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(help_text='물건번호')),
                ('property_name', models.CharField(blank=True, help_text='매물명(건물명)', max_length=255, null=True)),
                ('item_spec_url', models.CharField(blank=True, help_text='매각물건명세서URL', max_length=1000, null=True)),
                ('item_purpose', models.CharField(blank=True, help_text='물건용도', max_length=255, null=True)),
                ('valuation_amount', models.CharField(blank=True, help_text='감정평가액', max_length=255, null=True)),
                ('item_note', models.CharField(blank=True, help_text='물건비고', max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, help_text='물건상태', max_length=255, null=True)),
                ('auction_date', models.DateTimeField(blank=True, help_text='매각기일', null=True)),
                ('auction_failures', models.IntegerField(blank=True, default=0, help_text='유찰횟수', null=True)),
                ('item_image_url', models.URLField(blank=True, help_text='이미지URL', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'auction_item',
                'managed': True,
                'unique_together': {('item_number', 'case_number')},
            },
        ),
        migrations.CreateModel(
            name='AuctionParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, help_text='당사자구분', max_length=100, null=True)),
                ('party_name', models.CharField(blank=True, help_text='당사자명', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, help_text='비고', max_length=255, null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'auction_party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClaimDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, help_text='소재지', null=True)),
                ('claim_deadline', models.DateField(blank=True, help_text='배당요구종기일', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'claim_distribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, help_text='소재지', null=True)),
                ('listing_type', models.CharField(blank=True, help_text='목록구분', max_length=100, null=True)),
                ('details', models.TextField(blank=True, help_text='상세내역', null=True)),
                ('final_result', models.CharField(blank=True, help_text='종국결과', max_length=100, null=True)),
                ('final_date', models.DateField(blank=True, help_text='종국일자', null=True)),
                ('case_number', models.ForeignKey(db_column='case_number', help_text='사건번호', on_delete=django.db.models.deletion.CASCADE, to='app.auctioncase')),
            ],
            options={
                'db_table': 'property_listing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuctionSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(help_text='회차 (1차, 2차, 3차...)')),
                ('auction_date', models.DateTimeField(blank=True, help_text='매각기일', null=True)),
                ('decision_date', models.DateTimeField(blank=True, help_text='매각결정기일', null=True)),
                ('minimum_price', models.BigIntegerField(blank=True, help_text='최저가격', null=True)),
                ('result_status', models.CharField(blank=True, help_text='결과상태 (유찰/낙찰/기타)', max_length=50, null=True)),
                ('schedule_type', models.CharField(blank=True, help_text='기일 종류 (매각기일/매각결정기일/기타)', max_length=20, null=True)),
                ('auction_item', models.ForeignKey(help_text='물건정보', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.auctionitem')),
            ],
            options={
                'db_table': 'auction_schedule',
                'ordering': ['round_number'],
                'managed': True,
                'unique_together': {('auction_item', 'round_number')},
            },
        ),
    ]
