# Generated by Django 5.2.1 on 2025-05-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='property_name',
            field=models.CharField(blank=True, help_text='매물명(건물명)', max_length=255, null=True),
        ),
    ]
