# Generated by Django 5.2.1 on 2025-05-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction_date_1',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction_date_2',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction_date_3',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction_date_4',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='decision_date_1',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='decision_date_2',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='decision_date_3',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='decision_date_4',
        ),
        migrations.CreateModel(
            name='AuctionSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(help_text='회차 (1차, 2차, 3차...)')),
                ('auction_date', models.DateTimeField(blank=True, help_text='매각기일', null=True)),
                ('decision_date', models.DateTimeField(blank=True, help_text='매각결정기일', null=True)),
                ('minimum_price', models.BigIntegerField(blank=True, help_text='최저가격', null=True)),
                ('result_status', models.CharField(blank=True, help_text='결과상태 (유찰/낙찰/기타)', max_length=50, null=True)),
                ('auction_item', models.ForeignKey(help_text='물건정보', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.auctionitem')),
            ],
            options={
                'db_table': 'auction_schedule',
                'ordering': ['round_number'],
                'managed': True,
                'unique_together': {('auction_item', 'round_number')},
            },
        ),
    ]
