# Generated by Django 5.2 on 2025-05-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncase',
            name='case_status',
            field=models.CharField(blank=True, help_text='사건상태', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auctioncase',
            name='final_date',
            field=models.DateField(blank=True, help_text='종국일자', null=True),
        ),
        migrations.AddField(
            model_name='auctioncase',
            name='final_result',
            field=models.CharField(blank=True, help_text='종국결과', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='area_info',
            field=models.CharField(blank=True, help_text='면적정보 (전용/공용)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='building_area',
            field=models.CharField(blank=True, help_text='건물면적', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='building_name',
            field=models.CharField(blank=True, help_text='건물명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='current_min_price',
            field=models.BigIntegerField(blank=True, help_text='현재 최저매각가격', null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='deposit_amount',
            field=models.BigIntegerField(blank=True, help_text='입찰보증금', null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='floor_info',
            field=models.CharField(blank=True, help_text='층수정보', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='land_area',
            field=models.CharField(blank=True, help_text='토지면적', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='property_address',
            field=models.CharField(blank=True, help_text='매물주소', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='property_detail_address',
            field=models.CharField(blank=True, help_text='상세주소', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='property_type',
            field=models.CharField(blank=True, help_text='물건종류', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specification_url', models.URLField(blank=True, help_text='매각물건명세서 URL', null=True)),
                ('appraisal_url', models.URLField(blank=True, help_text='감정평가서 URL', null=True)),
                ('survey_url', models.URLField(blank=True, help_text='측량서 URL', null=True)),
                ('register_url', models.URLField(blank=True, help_text='등기부등본 URL', null=True)),
                ('auction_item', models.OneToOneField(help_text='물건정보', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.auctionitem')),
            ],
            options={
                'db_table': 'property_document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='이미지 URL')),
                ('image_order', models.IntegerField(default=0, help_text='이미지 순서')),
                ('is_main', models.BooleanField(default=False, help_text='메인 이미지 여부')),
                ('description', models.CharField(blank=True, help_text='이미지 설명', max_length=200, null=True)),
                ('auction_item', models.ForeignKey(help_text='물건정보', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.auctionitem')),
            ],
            options={
                'db_table': 'property_image',
                'ordering': ['image_order'],
                'managed': True,
            },
        ),
    ]
