# Generated by Django 5.2.1 on 2025-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_auctionitem_auction_date_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionschedule',
            name='schedule_type',
            field=models.CharField(blank=True, help_text='기일 종류 (매각기일/매각결정기일/기타)', max_length=20, null=True),
        ),
    ]
