# Generated by Django 5.2 on 2025-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auctioncase_case_status_auctioncase_final_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='building_name',
        ),
    ]
