# Generated by Django 5.2 on 2025-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_auctionitem_building_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='area_info',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='land_area',
        ),
    ]
