# Generated by Django 5.2 on 2025-05-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_auctionitem_area_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1)),
                ('address', models.TextField(blank=True)),
                ('building_type', models.CharField(default='집합건물', max_length=50)),
                ('building_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_details', to='app.auctionitem')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('auction_item', 'sequence')},
            },
        ),
    ]
