# Generated by Django 5.2 on 2025-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_buildingdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_num", models.BigIntegerField()),
                ("bidder_address", models.CharField(max_length=42)),
                ("bid_amount", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("trade_num", "bidder_address")},
            },
        ),
    ]
