# Generated by Django 5.2 on 2025-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_bidlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidlog",
            name="bid_time",
            field=models.DateTimeField(null=True),
        ),
    ]
