# Generated by Django 5.2 on 2025-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_bidlog_bid_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidlog",
            name="bid_security",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
