# Generated by Django 4.2.23 on 2025-06-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bidlog_bid_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='appraisal_url',
            field=models.URLField(blank=True, help_text='감정평가서 URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='register_url',
            field=models.URLField(blank=True, help_text='등기부등본 URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='specification_url',
            field=models.URLField(blank=True, help_text='매각물건명세서 URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='survey_url',
            field=models.URLField(blank=True, help_text='측량서 URL', max_length=500, null=True),
        ),
    ]
