# Generated by Django 4.2.23 on 2025-06-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_propertydocument_appraisal_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='appraisal_url',
            field=models.URLField(blank=True, help_text='감정평가서 URL', null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='register_url',
            field=models.URLField(blank=True, help_text='등기부등본 URL', null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='specification_url',
            field=models.URLField(blank=True, help_text='매각물건명세서 URL', null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='survey_url',
            field=models.URLField(blank=True, help_text='측량서 URL', null=True),
        ),
    ]
